from django.core.management.base import BaseCommand
from jewellery_api.models import Product

class Command(BaseCommand):
    help = 'Seed the database with sample jewelry products'

    def handle(self, *args, **options):
        products_data = [
            {
                'id': '1',
                'name': 'Classic Gold Wedding Ring',
                'description': 'Elegant 18k yellow gold wedding ring with a timeless design. Perfect for engagements, weddings, or special occasions.',
                'price': 1299.00,
                'material': '18k Yellow Gold',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': True,
            },
            {
                'id': '2',
                'name': 'Pearl Pendant Necklace',
                'description': 'Timeless freshwater pearl necklace set in 14k yellow gold. A classic piece that adds elegance to any outfit.',
                'price': 899.00,
                'material': 'Yellow Gold, Pearl',
                'category': 'necklaces',
                'imageUrl': 'https://images.pexels.com/photos/1458837/pexels-photo-1458837.jpeg?auto=compress&cs=tinysrgb&w=800',
                'inStock': True,
                'featured': True,
            },
            {
                'id': '3',
                'name': 'Gold Drop Earrings',
                'description': 'Exquisite 18k yellow gold drop earrings with elegant design. A stunning statement piece that adds sophistication to any outfit.',
                'price': 899.00,
                'material': '18k Yellow Gold',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1535632066927-ab7c9f2a3b76?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': True,
            },
            {
                'id': '4',
                'name': 'Gold Link Bracelet',
                'description': 'Luxurious 18k yellow gold link bracelet with classic design. Perfect for everyday elegance or special occasions.',
                'price': 1299.00,
                'material': '18k Yellow Gold',
                'category': 'bracelets',
                'imageUrl': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '6',
                'name': 'Gold Chain',
                'description': 'Classic 18k yellow gold chain necklace. Versatile and timeless design suitable for everyday wear.',
                'price': 1299.00,
                'material': 'Yellow Gold',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1721807550979-6e662d370e92?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1470',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '7',
                'name': 'Gold Stud Earrings',
                'description': 'Classic 18k yellow gold stud earrings. A must-have classic for every jewelry collection.',
                'price': 599.00,
                'material': '18k Yellow Gold',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '8',
                'name': 'Silver Charm Bracelet',
                'description': 'Beautiful sterling silver charm bracelet with customizable charms. Perfect for creating personal stories.',
                'price': 599.00,
                'material': 'Sterling Silver',
                'category': 'bracelets',
                'imageUrl': 'https://images.pexels.com/photos/1460838/pexels-photo-1460838.jpeg?auto=compress&cs=tinysrgb&w=800',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '9',
                'name': 'Ruby Eternity Ring',
                'description': 'Stunning ruby eternity ring in 18k yellow gold. Symbolizes eternal love and commitment.',
                'price': 2799.00,
                'material': 'Yellow Gold, Ruby',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1677466891119-2baa2f2ba447?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1974',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '10',
                'name': 'Layered Gold Necklace',
                'description': 'Trendy layered necklace in 14k yellow gold. Perfect for modern, fashion-forward looks.',
                'price': 799.00,
                'material': 'Yellow Gold',
                'category': 'necklaces',
                'imageUrl': 'https://images.pexels.com/photos/1458837/pexels-photo-1458837.jpeg?auto=compress&cs=tinysrgb&w=800',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '11',
                'name': 'Crystal Hoop Earrings',
                'description': 'Elegant crystal-embellished hoop earrings in sterling silver. Adds sparkle to any ensemble.',
                'price': 399.00,
                'material': 'Sterling Silver, Crystal',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1648291531524-97afa1c2ac30?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '12',
                'name': 'Infinity Bracelet',
                'description': 'Delicate infinity symbol bracelet in rose gold. Represents endless possibilities and love.',
                'price': 449.00,
                'material': 'Rose Gold',
                'category': 'bracelets',
                'imageUrl': 'https://images.pexels.com/photos/1458867/pexels-photo-1458867.jpeg?auto=compress&cs=tinysrgb&w=800',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '13',
                'name': 'Gold Ring',
                'description': '24 carat',
                'price': 12117.00,
                'material': 'Gold 24 Carat',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1731586249471-82bb9b2f769a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1974',
                'inStock': True,
                'featured': True,
            },
            # Additional Gold Jewelry
            {
                'id': '14',
                'name': 'Premium Gold Ring',
                'description': 'Exquisite 24k pure gold ring with intricate craftsmanship. A luxury piece for special occasions.',
                'price': 2999.00,
                'material': '24k Pure Gold',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': True,
            },
            {
                'id': '15',
                'name': 'Gold Statement Necklace',
                'description': 'Bold 18k yellow gold statement necklace with modern geometric design. Perfect for making a fashion statement.',
                'price': 1899.00,
                'material': '18k Yellow Gold',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '16',
                'name': 'Gold Hoop Earrings',
                'description': 'Classic 18k yellow gold hoop earrings in various sizes. Timeless elegance for any occasion.',
                'price': 799.00,
                'material': '18k Yellow Gold',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '17',
                'name': 'Gold Bangle Set',
                'description': 'Elegant set of 18k yellow gold bangles. Stackable design for a layered look.',
                'price': 1599.00,
                'material': '18k Yellow Gold',
                'category': 'bracelets',
                'imageUrl': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '18',
                'name': 'Gold Signet Ring',
                'description': 'Traditional 18k yellow gold signet ring. Perfect for engraving initials or family crest.',
                'price': 999.00,
                'material': '18k Yellow Gold',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            # Silver Jewelry Collection
            {
                'id': '19',
                'name': 'Silver Statement Ring',
                'description': 'Bold sterling silver statement ring with modern design. Perfect for contemporary style.',
                'price': 299.00,
                'material': 'Sterling Silver',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '20',
                'name': 'Silver Pendant Necklace',
                'description': 'Elegant sterling silver pendant necklace with intricate design. A versatile piece for everyday wear.',
                'price': 199.00,
                'material': 'Sterling Silver',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '21',
                'name': 'Silver Drop Earrings',
                'description': 'Beautiful sterling silver drop earrings with elegant design. Perfect for both casual and formal occasions.',
                'price': 149.00,
                'material': 'Sterling Silver',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1535632066927-ab7c9f2a3b76?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '22',
                'name': 'Silver Chain Bracelet',
                'description': 'Classic sterling silver chain bracelet with adjustable length. A timeless piece for any wardrobe.',
                'price': 99.00,
                'material': 'Sterling Silver',
                'category': 'bracelets',
                'imageUrl': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '23',
                'name': 'Silver Stud Earrings',
                'description': 'Simple and elegant sterling silver stud earrings. A must-have for every jewelry collection.',
                'price': 79.00,
                'material': 'Sterling Silver',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '24',
                'name': 'Silver Cuff Bracelet',
                'description': 'Modern sterling silver cuff bracelet with contemporary design. Perfect for making a style statement.',
                'price': 199.00,
                'material': 'Sterling Silver',
                'category': 'bracelets',
                'imageUrl': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            # More Gold Jewelry
            {
                'id': '25',
                'name': 'Gold Chain Necklace',
                'description': 'Luxurious 18k yellow gold chain necklace with classic link design. A versatile piece for layering or wearing alone.',
                'price': 899.00,
                'material': '18k Yellow Gold',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '26',
                'name': 'Gold Cocktail Ring',
                'description': 'Statement 18k yellow gold cocktail ring with bold design. Perfect for special occasions and evening wear.',
                'price': 1299.00,
                'material': '18k Yellow Gold',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            # Additional 10 Products
            {
                'id': '27',
                'name': 'Gold Heart Pendant',
                'description': 'Romantic 18k yellow gold heart pendant on a delicate chain. Perfect for expressing love and affection.',
                'price': 699.00,
                'material': '18k Yellow Gold',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '28',
                'name': 'Silver Heart Earrings',
                'description': 'Sweet sterling silver heart-shaped earrings. A romantic gift for any special someone.',
                'price': 89.00,
                'material': 'Sterling Silver',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1535632066927-ab7c9f2a3b76?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '29',
                'name': 'Gold Vintage Ring',
                'description': 'Antique-style 18k yellow gold vintage ring with intricate filigree design. A timeless piece with character.',
                'price': 1199.00,
                'material': '18k Yellow Gold',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '30',
                'name': 'Silver Infinity Necklace',
                'description': 'Elegant sterling silver infinity symbol necklace. Represents endless love and possibilities.',
                'price': 129.00,
                'material': 'Sterling Silver',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '31',
                'name': 'Gold Chandelier Earrings',
                'description': 'Dramatic 18k yellow gold chandelier earrings with cascading design. Perfect for special occasions.',
                'price': 1499.00,
                'material': '18k Yellow Gold',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1535632066927-ab7c9f2a3b76?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '32',
                'name': 'Silver Tennis Bracelet',
                'description': 'Classic sterling silver tennis bracelet with smooth links. A versatile piece for everyday elegance.',
                'price': 249.00,
                'material': 'Sterling Silver',
                'category': 'bracelets',
                'imageUrl': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '33',
                'name': 'Gold Locket Necklace',
                'description': 'Vintage-style 18k yellow gold locket necklace. Perfect for holding precious memories and photos.',
                'price': 899.00,
                'material': '18k Yellow Gold',
                'category': 'necklaces',
                'imageUrl': 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '34',
                'name': 'Silver Pearl Earrings',
                'description': 'Elegant sterling silver earrings with freshwater pearls. A classic combination of silver and pearl beauty.',
                'price': 179.00,
                'material': 'Sterling Silver, Pearl',
                'category': 'earrings',
                'imageUrl': 'https://images.unsplash.com/photo-1535632066927-ab7c9f2a3b76?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '35',
                'name': 'Gold Cuff Links',
                'description': 'Sophisticated 18k yellow gold cuff links with classic design. Perfect for formal occasions and business attire.',
                'price': 799.00,
                'material': '18k Yellow Gold',
                'category': 'rings',
                'imageUrl': 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
            {
                'id': '36',
                'name': 'Silver Anklet',
                'description': 'Delicate sterling silver anklet with adjustable chain. A subtle and elegant piece for summer style.',
                'price': 69.00,
                'material': 'Sterling Silver',
                'category': 'bracelets',
                'imageUrl': 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1000',
                'inStock': True,
                'featured': False,
            },
        ]

        # Clear existing products
        Product.objects.all().delete()
        self.stdout.write('Cleared existing products...')

        # Create new products
        for product_data in products_data:
            Product.objects.create(**product_data)
            self.stdout.write(f'Created product: {product_data["name"]}')

        self.stdout.write(
            self.style.SUCCESS(f'Successfully seeded {len(products_data)} products!')
        )
