# Generated by Django 5.2.7 on 2025-10-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery_api', '0002_order_billing_address_order_notes_order_session_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'session_id')},
        ),
    ]
